### ISSUE TITLE
What version of SFML does CSFML 2.3 support?

### ISSUE THREAD

**Issue by madhu-GG** [SFML/CSFML#111]
I downloaded CSFML 2.3 and SFML 2.3. But while compiling I got the following error:

``` bash
$gcc -Wall -Wextra -Werror -o test main.o -L/opt/csfml-2.3/lib -lcsfml-graphics -lcsfml-window -lcsfml-system -L/opt/sfml-2.3/lib -lsfml-graphics -lsfml-window -lsfml-system
```

```
/usr/bin/ld: warning: libsfml-graphics.so.2.2, needed by /opt/csfml-2.3/lib/libcsfml-graphics.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libsfml-window.so.2.2, needed by /opt/csfml-2.3/lib/libcsfml-graphics.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libsfml-system.so.2.2, needed by /opt/csfml-2.3/lib/libcsfml-graphics.so, not found (try using -rpath or -rpath-link)
```

according to the bindings page CSFML 2.3 requires SFML 2.3. I am confused!

**Comment by mantognini** [comment]
I very quickly checked the pre-built 64-bit binaries for CSFML 2.3, and indeed `ldd` shows references to SFML 2.2 instead of 2.3. So there's indeed a bug there.

Now, those pre-built packages are probably not the best way to get (C)SFML on your system. They highly depends on the environment used to build them, so if yours is slightly different you might have some incompatibility issues.

I'd say the best way to get (C)SFML on Linux is to build them yourself. It's actually not that hard if you follow the official tutorials. It will also allow you to test the latest version, which should be in sink with SFML 2.4 now. Without testing we can't really release it. ;-)

**Comment by madhu-GG** [comment]
I have successfully built CSFML 2.3 with SFML 2.4. Everything seems to be alright. My test runs. :smile:

**Comment by madhu-GG** [comment]
Sorry, My issue was solved. So I made the mistake of closing the ticket. But the bug is still present so I will reopen the issue. Please forgive the inconvenient auto-emails.

**Comment by eXpl0it3r** [comment]
We decided to not provide pre-built Linux binaries anymore and to prevent the mentioned issue here also removed the ones for CSFML 2.3.

Linux has a built-in package manager which should in most cases be preferred over any other packages and if the most recent changes are required, then it's way better to build from source, as it's pretty much impossible to guarantee that provided binaries will work on any Linux distro out there.
