### ISSUE TITLE
Missing getTransform and getInverseTransform in sfView

### ISSUE THREAD

**Issue by Urgau** [SFML/CSFML#135]
Hello,

it seems to missing sfView_getTransform and sfView_getInverseTransform.
Can you please add it.

**Comment by LaurentGomila** [comment]
If you look at the documentation of the C++ API for these functions, you can see the following comment:

```cpp
/// This function is meant for internal use only.
```

In other words, they are public only because some other classes of SFML need to call them, but they should never be useful for the end user. That's why they are not part of the C binding.

May I ask why you need them?

**Comment by Urgau** [comment]
Sorry I didn't see it.
I try to make a tile map in isometric view with a sfRenderTexture and a sfView and I want to some have objects on the map but I don't want the objects to be distorted so I have to idea to apply the inverse transformation to the objects so a the draw moment the transformation done by the sfView is none (like there was no transformation).

**Comment by LaurentGomila** [comment]
The solution in this case is simply to use another view to draw these objects.

**Comment by eXpl0it3r** [comment]
The functions are meant for internal use and as such are not exposed to the CSFML API. I'll close this issue for now.
