### ISSUE TITLE
Requesting new release

### ISSUE THREAD

**Issue by crumblingstatue** [SFML/CSFML#157]
I released a new version of rust-sfml, and someone using windows seems to be [having problems](https://github.com/jeremyletang/rust-sfml/issues/235) with `undefined reference to sfRenderTexture_createWithSettings`.
There was a [pull request](https://github.com/SFML/CSFML/pull/137) that fixed an incorrect header signature, but it seems that no new release has been made since then.

Thank you for considering!

**Comment by eXpl0it3r** [comment]
I fully agree!

Maybe you can help me out with some of the stuff needed:

- [ ] Double check that the master branch hasn't implemented any 2.6 features already
- [ ] Double check that all the 2.5.x APIs are now properly implemented
- [ ] Create a [build script](https://github.com/SFML/CSFML/tree/master/tools/nuget) for macOS, so we can ship NuGet builds for macOS as well.

**Comment by crumblingstatue** [comment]
I can help with the first 2, but I don't have any knowledge or interest to help with Mac OS specific stuff.

**Comment by eXpl0it3r** [comment]
That's okay. It also requires access to a macOS machine, so not a task for everyone. 
I'll try to look into that task, since I do have access to our SFML Mac Minis and some older CSFML build script, that I might be able to adjust.

If you can double check the state of master, I'd highly appreciate it.
Focus should be mainly that we don't release SFML 2.6 related stuff, if there's still something missing for SFML 2.5.x we could always create another release.

**Comment by crumblingstatue** [comment]
I reviewed [the changes](https://github.com/SFML/CSFML/compare/2.5...master), there is no change that added SFML 2.6 related stuff.

**Comment by nulldg** [comment]
I would appreciate a new release for the same reason. Any updates so far?

**Comment by eXpl0it3r** [comment]
CSFML 2.5.1 [has been released](https://github.com/SFML/CSFML/tree/2.5.1) 🎉
