### ISSUE TITLE
Problem building on Debian Bookworm

### ISSUE THREAD

**Issue by klutt** [SFML/CSFML#174]
I ran `sudo apt-get install libsfml-dev libcsfml-dev`

Then I created this simple program:

```                                                 
➜  gfx cat test.c             
#include <SFML/Graphics.h>
#include <stdio.h>

int main()
{
    sfVideoMode mode = {800, 600, 32};
    sfRenderWindow* window;
    sfEvent event;

    perror("Starting program");
    
    /* Create the main window */
    window = sfRenderWindow_create(mode, "SFML window", sfResize | sfClose, NULL);
    if (!window) {
	perror("Error creating window");
        return 1;
    }

    perror("Entering loop");

    /* Process events */
    while(sfRenderWindow_pollEvent(window, &event))
    {
	/* Close window : exit */
	if (event.type == sfEvtClosed)
	    sfRenderWindow_close(window);

	        /* Clear the screen */
        sfRenderWindow_clear(window, sfBlack);
	    
	sfRenderWindow_display(window);
    }

    perror("Cleaning up");
    
    sfRenderWindow_destroy(window);

    perror("Exiting");
}
➜  gfx 
```
Compile and run:
```
➜  gfx gcc test.c -lcsfml-graphics -lcsfml-window
➜  gfx ./a.out                                   
Starting program: Success
Entering loop: Resource temporarily unavailable
Cleaning up: Resource temporarily unavailable
Exiting: Resource temporarily unavailable
➜  gfx 
```
I see a window flashing for a split second, but that's all.

I read that this might be because of different versions for sfml and csfml, so here is that info:
```
➜  gfx apt list libsfml-dev libcsfml-dev
Listing... Done
libcsfml-dev/jammy,now 2.5-1.1 amd64 [installed]
libsfml-dev/jammy,now 2.5.1+dfsg-2 amd64 [installed]
```
Is that enough of a difference to cause problems? In that case, I assume there is an issue with the debian packages?

For completeness:
```
➜  gfx cat /etc/debian_version
bookworm/sid
➜  gfx 
```

**Comment by initxz** [comment]
> I see a window flashing for a split second, but that's all.

This is the expected behaviour.

Read the documentation on what "sfRenderWindow_pollEvent" does [Returns true... or _false if the event queue was empty_]
https://www.sfml-dev.org/documentation/2.5.1/classsf_1_1RenderWindow.php#a338e996585faf82e93069858e3b531b7

The correct code would be (taken from csfml documentation):


    while (sfRenderWindow_isOpen(window))
    {
        /* Process events */
        while (sfRenderWindow_pollEvent(window, &event))
        {
            /* Close window : exit */
            if (event.type == sfEvtClosed)
                sfRenderWindow_close(window);
        }
 
        /* Clear the screen */
        sfRenderWindow_clear(window, sfBlack);
 
        /* Draw the sprite */
        sfRenderWindow_drawSprite(window, sprite, NULL);
 
        /* Draw the text */
        sfRenderWindow_drawText(window, text, NULL);
 
        /* Update the window */
        sfRenderWindow_display(window);
    }

In Debian you can find this in /usr/share/doc/libcsfml-dev/html/index.html

**Comment by eXpl0it3r** [comment]
As pointed out, you need to properly handle events, otherwise the window may just close, as the event isn't initialized, you have undefined behavior and thus the if might just return true.

I'll close this for now, if you need further help, please post on [the forum](https://en.sfml-dev.org/forums/index.php?board=12.0) or join our [Discord server](https://discord.gg/nr4X7Fh).
