### ISSUE TITLE
Generated CSFML documentation does not document any functions

### ISSUE THREAD

**Issue by jcowgill** [SFML/CSFML#210]
The generated CSFML documentation doesn't actually document any functions. It only seems to document structures which you can see under the "Classes" tab.

This may be related to https://github.com/SFML/SFML/issues/2813. I would expect the functions to appear under the file list, but if the file list is broken then maybe it's not surprising that no functions from those files are documented. In SFML it's not too bad though because the class documentation is still there.

### Some pictures

The black links are not clickable.
![image](https://github.com/SFML/CSFML/assets/1226825/e9fa2f98-3d92-469c-bff5-fb62f4301f19)

![image](https://github.com/SFML/CSFML/assets/1226825/d5c5f081-1ed1-4f3a-9212-4c3b72106315)

Structures are documented but not the functions associated with them:
![image](https://github.com/SFML/CSFML/assets/1226825/b67efad0-4d41-4909-aedf-9cc146cc409a)

**Comment by eXpl0it3r** [comment]
Turns out this is a common "issue" given that it's close to the top of the [doxygen FAQ](https://www.doxygen.nl/manual/faq.html)

We have to options, either document the whole file with `\file`:
![image](https://github.com/SFML/CSFML/assets/920861/9728f0d2-a6b8-42d4-9ccf-2266b6833aa0)

Or create our own grouping of groups, which also would allow us to document more things:
![image](https://github.com/SFML/CSFML/assets/920861/5198acbc-9407-451a-9277-8059626a448d)  
![image](https://github.com/SFML/CSFML/assets/920861/fdfcfdc9-7a84-45ab-bbd7-9b8d43116148)

**Comment by eXpl0it3r** [comment]
Fixed in #246

It's not necessarily a perfect solution, since you don't get a nice grouping, but it's the easier solution for now and should now include all the functions.
